# Generated by Django 5.2.9 on 2025-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(max_length=50, unique=True, verbose_name='ID на HH')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('employer_name', models.CharField(blank=True, max_length=300, verbose_name='Работодатель')),
                ('area_name', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ЗП от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ЗП до')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='Валюта')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на HH')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
