# Generated by Django 5.2.9 on 2025-12-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='created_at',
        ),
    ]
